Catch IndexError if fits on linecuts are not successful
carnisj/bcdi pull request #272
Opened 2022-06-17 14:30 UTC by DSimonne

Trying to catch the error to prevent the bog on the linecut.

This needs some testing first

2022-06-17 15:19 UTC, DSimonne commented
So it fixed the issue for MIR !

2022-06-17 18:30 UTC, carnisj requested changes

2022-06-17 18:30 UTC, carnisj commented on bcdi/graph/graph_utils.py
> +        plt.close()
Looks good, can you just close explicitely the opened figure as follows and add a message:

```suggestion
        print("Automatic fitting of linecuts failed.")
        plt.close(fig)
```

2022-06-17 21:59 UTC, DSimonne commented
I authorized your changes, I don't know why I cannot go through with it, maybe you need to review again ?

2022-06-18 06:22 UTC, carnisj approved these changes

2022-06-18 06:22 UTC, merged