Support new detector at SixS and new alias dict
carnisj/bcdi pull request #279
Opened 2022-07-12 20:49 UTC by DSimonne

I created a new detector for SixS, added a new alias dict and fixed a pb in the rocking curve function.

This was tested locally but before the big id 27 changes

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update
- [ ] Documentation update

## How has this been tested?
Multiple scan processed during beamtime with gwaihir

**Test Configuration**:

Debian 11

## Checklist:

- [ ] I have made corresponding changes to the documentation
- [ ] I have added corresponding unit tests
- [x] I have run ``doit`` and all tasks have passed

2022-07-13 14:30 UTC, clatlan commented
I also wonder about the horizontal configuration.

Now at SixS we mostly use the vertical configuration, so I flip the data before preprocessing as you had adviced before (the detail is in `gwaihir.controller.control_startup.rotate_sixs_data()`).

But the rocking curve is perfomed outofplane for most of the scans;
* we are using the 111 reflection,
* the sample is vertical, 
* the inplane rocking angle is omega,
* to move the detector inplane is delta and outofplane gamma.
* we perform the rocking curve with mu, also outofplane (basically mu and gamma are in a theta - two theta geometry perpendicular to the sample plane)

However bcdi does not support outofplane for the rocking_angle parameter.

And in strain.py, the value of omega and gamma are switched (we are at mu ~ 19 deg and gamma ~ 38 deg)

```python
INFO:bcdi.preprocessing.process_scan:Detector angles before correction: inplane 37.44 deg, outofplane 0.17 deg
INFO:bcdi.preprocessing.process_scan:Corrected detector angles: inplane 37.77 deg, outofplane 0.32 deg
INFO:bcdi.preprocessing.process_scan:Wavevector transfer of Bragg peak: [-0.90276104  0.0242599   2.63858146], Qnorm=2.7888
```

I'm not sure everything is right ?

I can put the data on the esrf if you would like to test ?

2022-07-15 09:22 UTC, DSimonne commented
Hi,

Oh ok I thought you had said it was best to rotate the diffraction pattern prior to the analysis, otherwise I'm not sure why I would have included that, I will try both approach and see the differences.

Thank you!

2022-07-18 09:18 UTC, DSimonne commented
## What I introduced
* new detector (MerlinSixS)
* changed the way the COM is found in bcdi_utils
* create a mask when showing the rocking curve to skip duplicate values in the tilt angles
* fix binning issue when only in the direction of the rocking curve (the data was unbinned also in the rocking curve direction without having binned before), I also changed the test

bcdi_utils.py, line 1155
```
    ####################################################################################
    # bin data and mask in the detector plane if not already done during loading       #
    # binning in the stacking dimension is done at the very end of the data processing #
    ####################################################################################
```

So maybe we need to move the binning in the rocking curve before so that the tests make more sense ?
Perhaps I missed smtg ...

2022-07-21 19:33 UTC, carnisj commented
Ok in principle for adding the detector and the new alias_dict. Please remove the part about the method `find_bragg` and open an issue f you think there is one. This is not within the scope of this Pull Request and is also conflicting with changes applied on this function recently. We can have a look at this separately. Please also rebase onto the main branch.

2022-07-21 19:35 UTC, carnisj commented on bcdi/preprocessing/bcdi_utils.py
> +
These modifications are not in the scope of the pull request, address it in an issue if needed.

2022-07-21 19:36 UTC, carnisj commented on bcdi/preprocessing/process_scan.py
> +        logger.info("Plotting the rocking curve.")
This message does not bring anything, an be removed

2022-07-21 19:37 UTC, carnisj requested changes

2022-07-21 19:37 UTC, carnisj commented on tests/preprocessing/test_bcdi_utils.py
>              data=self.data, peak_method="max", roi=(3, 3, 4, 2), binning=(3, 3, 4)
the tests relative to `find_bragg` are also not in the scope of this pull request.

2022-07-22 08:05 UTC, DSimonne commented
Hi,
I think I rebased it ? But now it shows more changes which is weird bc these changes are already in your main branch right?
I'm not sure if it's right =D

2022-07-23 06:08 UTC, carnisj approved these changes

2022-07-23 06:08 UTC, merged